### ISSUE TITLE
Remove /opt/clusterware NFS exports/mounts

### ISSUE THREAD

**Issue by mjtko** [alces-software/symphony#1]
Clusterware is now locally installed on every node that requires it so we should:
1. Remove it from the symphony-app `/etc/exports` file.
2. Modify configuration to stop it from being mounted on appliances/nodes.

**Comment by vlj91** [comment]
Remove from symphony-director - `/etc/puppet/environments/symphony/hieradata/site.yaml`: 

``` yaml
 'symphony-app.mgt.symphony.local:/opt/clusterware':
   target: '/opt/clusterware'
   options: intr,rsize=32768,wsize=32768,_netdev
```

Remove from symphony-app - `/etc/exports`:

``` bash
/opt/clusterware/ 10.78.0.0/16(ro,no_root_squash,no_subtree_check,sync)
```
